config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  	:registrations => 'users/registrations',
  	:sessions => 'users/sessions'
  }
  resources :articles
  root "articles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
	
	attachmet :image
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :articles, dependent: :destroy

  delegate :name, to: :profile, prefix: :auther, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:show, :edit, :update, :destroy]

  def index
  	@articles = current_user.articles.order(created_at: :desc)
  end

  def show
  	@article = Article.find(params[:id])
  end

  def edit
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)
    @article.user_id = current_user.id
  	if @article.save
  		redirect_to @article, notice: '作成に成功しました。'
  	else
  		render :new, alert: '作成できませんでした。'
  	end
  end

  def update
  	if @article.update(artilce_params)
  		redirect_to @artilce, notice: '更新に成功しました。'
  	else
  		render :edit, alert: '更新できませんでした。'
  	end
  end

  def destroy
  	if @article.destroy
  		redirect_to root_path, notice: '削除に成功しました。'
  	else
  		redirect_to root_path, alert: '削除できませんでした。'
  	end
  end

  private
  def find_article
  	@article = Article.find(params[:id])
  end

  def artilce_params
  	params.repuire(:article).permit(:title, :body, :image)
  end

  def validate_user
    if @article.user != current_user
      redirect_to root_path, alert: '自分の投稿ではありません'
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  POST /resource
   def create
    super
    if resource
      resource == user
      profile = Profile.new
      profile.user_id = resource.id
      profile.name = params[:profile][:name]
      profile.save
      resource.profile.create(name: params[:profile][:name])
    end
    puts "====#{params[:profile][:name]}===="
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<% form_for article do %>

　<div id="cover-image" class="form-group padding-to-15 relative">
	<% if article.image_id.present? %>
	  <%= image_tag attachment_url(article, :image), class: 'article-image' %>
	<% else %>
	  <%= image_tag 'no-image.jpeg', class: 'article-image' %>
	<% end %>
	<i class="fa fa-camera"></i>
  </div>

  <%= f.attachment_field :image %>

  <div class="form-group padding-top-15">
  	<%= f.attachment_field :image %>
  </div>

  <div class="form_group padding-top-15">
  	<%= f.label :title, 'タイトル' %>
  	<%= f.text_feeld :title, class: 'form_control' %>
  </div>
  <div class="form_group">
  	<%= f.label :body, '本文' %>
  	<%= f.text_feeld :body, class: 'form_control' %>
  </div>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
	<div class="col-md-4 margin-top-5per article-back">
		<%= image_tag 'hukurou.jpeg', class: "article-image padding-top-15" %>
		<h1 class="text-center">ブログの編集</h1>
		<div class="padding-bottom-15">
		  <p class="title"><%= @article.title %></p>
		  <span class="text-right">
		  	<%= @article.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
		  </span>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1 class="text-center">ブログ</h1>
  <% @articles.each do |article| %>
	<%= link_to article do %>
	<div class="col-md-4 margin-top-5per article-back">
		<% if @article.image_id.present? %>
          <%= image_tag attachment_url(@article, :image), class: 'article-image padding-top-15 article-list-image' %>
        <% else %>
          <%= image_tag 'hukurou.jpeg', class: "img-responsive padding-top-15 article-list-image" %>
        <% end %>
		<div class="padding-bottom-15">
		  <p class="title"><%= article.title %></p>
		  <span>
		  	<%= article.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
		  </span>
		</div>
	</div>
	<% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="container">
	<div class="col-md-4 margin-top-5per article-back">
	    <h1 class="text-center">ブログの新規作成</h1>
		<%= image_tag 'hukurou.jpeg', class: "article-image padding-top-15" %>
		<div class="padding-bottom-15">
			<%= render 'form', article: @article %>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="container">
	<div class="col-md-4 margin-top-5per article-back">

        <% if @article.image_id.present? %>
          <%= image_tag attachment_url(@article, :image), class: 'article-image padding-top-15 article-list-image' %>
        <% else %>
          <%= image_tag 'hukurou.jpeg', class: "img-responsive padding-top-15 article-list-image" %>
        <% end %>

		<h1 class="text-center"><%= @article.title %></h1>
		<div class="padding-bottom-15">
		  <p class="title"><%= @article.title %></p>
		  <span class="text-right">
		  	<%= @article.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
		  </span>
		</div>
		<%= link_to '編集', edit_article_path(@article), class: 'btn btn-primary', style: 'margin-bottom: 10px' %>
		<%= link_to '削除', article_path(@article), method: :delete, data: {confirm: '削除してもよろしいですか？'}, class: 'btn btn-danger', style: 'margin-bottom: 10px' %>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <div>
      <a class="navbar-brand" href="#">ブログ</a>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", %></li>
        <li><%= link_to "Help", %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
      </div>
      <div>
        <% if user_signed_in? %>
          <a class="navbar-brand" href="/"><% current_user.name %>のブログ</a>
        <% else %>
          <a class="navbar-brand" href="/">ブログサービス</a>
        <% end %>
      </div>
    </nav>
    <div class="cllapse navbar-collapse" id="navigation">
      <% if user_signed_in? %>
        <%= link_to '新規作成' new_article_path %>
        <%= link_to 'ログアウト' destroy_user_session_path %>
      <% else %>
        <%= link_to 'ユーザー登録' new_user_registration_path %>
        <%= link_to 'ログイン' new_user_session_path %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>BlogTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0,maximum-scale=10.0, user-scalable=yes">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/header' %>

  <!-- 新規登録やログイン時に -->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>